In [13]:
import pandas as pd

df=pd.read_csv(r'C:\Users\hp zbook\homewok\four\command.csv') 


print(df.head())


                                               Title  \
0                           Wonderful place to stay.   
1                                      It was superb   
2                                          Very Good   
3                                          Wonderful   
4  Fantastic value for a new, modern and spotless...   

                                            Positive         Negative  Score  \
0  New, comfortable apartments, close to the airp...  Nothing at all.   10.0   
1  We had a really pleasant stay! The staff was v...              NaN   10.0   
2  the location is great and near the airport. bu...              NaN    8.0   
3            Great stuff\nGreat Quality/price\nClean              NaN    9.0   
4  Clean and modern with very comfortable beds, i...              NaN   10.0   

    GuestName    GuestCountry                   RoomType NumberOfNights  \
0        Olga          Norway           Budget Twin Room        1 night   
1       Iwona          Poland   

In [15]:
df['spam']=df['Title'].apply(lambda x:1 if x=='spam'else 0)
df

Title  \
0                              Wonderful place to stay.   
1                                         It was superb   
2                                             Very Good   
3                                             Wonderful   
4     Fantastic value for a new, modern and spotless...   
...                                                 ...   
1518                                        Exceptional   
1519                                          Wonderful   
1520                                          Very Good   
1521                                          Wonderful   
1522                                           Pleasant   

                                               Positive         Negative  \
0     New, comfortable apartments, close to the airp...  Nothing at all.   
1     We had a really pleasant stay! The staff was v...              NaN   
2     the location is great and near the airport. bu...              NaN   
3               Great stuff\nGreat Quality/price\nClean              NaN   
4     Clean and modern with very comfortable beds, i...              NaN   
...                                                 ...              ...   
1518                                                NaN              NaN   
1519                                                NaN              NaN   
1520                                                NaN              NaN   
1521                                                NaN              NaN   
1522                                                NaN              NaN   

      Score   GuestName    GuestCountry                   RoomType  \
0      10.0        Olga          Norway           Budget Twin Room   
1      10.0       Iwona          Poland                Double Room   
2       8.0      Ruijia          Sweden                Double Room   
3       9.0  Theprincem  United Kingdom   Double Room with Balcony   
4      10.0           M     Switzerland  Family Suite with Balcony   
...     ...         ...             ...                        ...   
1518   10.0   Anonymous          Israel                        NaN   
1519    9.0   Anonymous  Czech Republic                        NaN   
1520    8.0   Anonymous          Sweden                        NaN   
1521    9.0   Anonymous         Germany                        NaN   
1522    6.0   Anonymous         Austria                        NaN   

     NumberOfNights VisitDate      GroupType PropertyResponse  spam  
0           1 night    Mar-22  Solo traveler              NaN     0  
1          3 nights    May-22         Family              NaN     0  
2           1 night    Dec-22  Solo traveler              NaN     0  
3          2 nights    Sep-22  Solo traveler              NaN     0  
4           1 night    Oct-22         Family              NaN     0  
...             ...       ...            ...              ...   ...  
1518       5 nights    Sep-21         Couple              NaN     0  
1519        1 night    Sep-21          Group              NaN     0  
1520        1 night    Aug-21         Couple              NaN     0  
1521       3 nights    Sep-21  Solo traveler              NaN     0  
1522        1 night    Oct-22         Couple              NaN     0  

[1523 rows x 12 columns]

In [16]:
dataset=df.drop(['Title'],axis='columns',errors='ingnore')
dataset

Positive         Negative  \
0     New, comfortable apartments, close to the airp...  Nothing at all.   
1     We had a really pleasant stay! The staff was v...              NaN   
2     the location is great and near the airport. bu...              NaN   
3               Great stuff\nGreat Quality/price\nClean              NaN   
4     Clean and modern with very comfortable beds, i...              NaN   
...                                                 ...              ...   
1518                                                NaN              NaN   
1519                                                NaN              NaN   
1520                                                NaN              NaN   
1521                                                NaN              NaN   
1522                                                NaN              NaN   

      Score   GuestName    GuestCountry                   RoomType  \
0      10.0        Olga          Norway           Budget Twin Room   
1      10.0       Iwona          Poland                Double Room   
2       8.0      Ruijia          Sweden                Double Room   
3       9.0  Theprincem  United Kingdom   Double Room with Balcony   
4      10.0           M     Switzerland  Family Suite with Balcony   
...     ...         ...             ...                        ...   
1518   10.0   Anonymous          Israel                        NaN   
1519    9.0   Anonymous  Czech Republic                        NaN   
1520    8.0   Anonymous          Sweden                        NaN   
1521    9.0   Anonymous         Germany                        NaN   
1522    6.0   Anonymous         Austria                        NaN   

     NumberOfNights VisitDate      GroupType PropertyResponse  spam  
0           1 night    Mar-22  Solo traveler              NaN     0  
1          3 nights    May-22         Family              NaN     0  
2           1 night    Dec-22  Solo traveler              NaN     0  
3          2 nights    Sep-22  Solo traveler              NaN     0  
4           1 night    Oct-22         Family              NaN     0  
...             ...       ...            ...              ...   ...  
1518       5 nights    Sep-21         Couple              NaN     0  
1519        1 night    Sep-21          Group              NaN     0  
1520        1 night    Aug-21         Couple              NaN     0  
1521       3 nights    Sep-21  Solo traveler              NaN     0  
1522        1 night    Oct-22         Couple              NaN     0  

[1523 rows x 11 columns]

In [17]:
print(df.groupby('spam').describe())

       Score                                               
       count      mean       std  min  25%  50%   75%   max
spam                                                       
0     1523.0  8.973802  1.300178  1.0  8.0  9.0  10.0  10.0


In [18]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(dataset,test_size=0.2,random_state=42)
print(train.shape)

(1218, 11)


In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
vectorizer=CountVectorizer()
train_vector=vectorizer.fit_transform(train.Positive.fillna(''))
print(train_vector.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(train_vector,train.spam)

MultinomialNB()

In [23]:
test_vector=vectorizer.transform(test.Positive.fillna(''))
print(test_vector.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [24]:
emails=['  Wonderful place to stay.']
emails_vector=vectorizer.transform(emails)
emails_vector

<1x1517 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [25]:
predictions=model.predict(emails_vector)
print(predictions)

[0]
